#!/usr/bin/env python3
"""
Setup script for Supabase integration with AgenticMemory.

This script helps users set up their Supabase database and configure
the environment for the AgenticMemory system.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional


def print_header(title: str):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f" {title}")
    print("=" * 60)


def print_step(step: str):
    """Print a formatted step."""
    print(f"\n→ {step}")


def print_success(message: str):
    """Print a success message."""
    print(f"✅ {message}")


def print_error(message: str):
    """Print an error message."""
    print(f"❌ {message}")


def print_warning(message: str):
    """Print a warning message."""
    print(f"⚠️  {message}")


def check_python_version():
    """Check if Python version is compatible."""
    print_step("Checking Python version...")
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print_error(f"Python 3.8+ required, but found {version.major}.{version.minor}")
        return False
    print_success(f"Python {version.major}.{version.minor}.{version.micro} - OK")
    return True


def check_supabase_cli():
    """Check if Supabase CLI is installed."""
    print_step("Checking Supabase CLI...")
    try:
        result = subprocess.run(
            ["supabase", "--version"], capture_output=True, text=True
        )
        if result.returncode == 0:
            version = result.stdout.strip()
            print_success(f"Supabase CLI found: {version}")
            return True
        else:
            print_error("Supabase CLI not found")
            return False
    except FileNotFoundError:
        print_error("Supabase CLI not found")
        return False


def install_supabase_cli():
    """Install Supabase CLI."""
    print_step("Installing Supabase CLI...")
    print("Please install Supabase CLI using one of these methods:")
    print("\n1. Using npm:")
    print("   npm install -g supabase")
    print("\n2. Using curl (Linux/macOS):")
    print("   curl -sSfL https://supabase.com/docs/reference/cli/install | bash")
    print("\n3. Using Homebrew (macOS):")
    print("   brew install supabase/tap/supabase")
    print("\n4. Download from: https://github.com/supabase/cli/releases")

    input("\nPress Enter after installing Supabase CLI...")
    return check_supabase_cli()


def create_env_file():
    """Create or update .env file with Supabase configuration."""
    print_step("Setting up environment variables...")

    env_file = Path(".env")
    env_config = {}

    # Load existing .env if it exists
    if env_file.exists():
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_config[key] = value

    # Get Supabase configuration
    print("\nPlease provide your Supabase configuration:")
    print("(You can find these in your Supabase project dashboard)")

    supabase_url = input(
        f"Supabase URL [{env_config.get('SUPABASE_URL', '')}]: "
    ).strip()
    if supabase_url:
        env_config["SUPABASE_URL"] = supabase_url

    supabase_key = input(
        f"Supabase Anon Key [{env_config.get('SUPABASE_ANON_KEY', '')}]: "
    ).strip()
    if supabase_key:
        env_config["SUPABASE_ANON_KEY"] = supabase_key

    service_role_key = input(
        f"Supabase Service Role Key (optional) [{env_config.get('SUPABASE_SERVICE_ROLE_KEY', '')}]: "
    ).strip()
    if service_role_key:
        env_config["SUPABASE_SERVICE_ROLE_KEY"] = service_role_key

    # Get OpenAI API key if not set
    if "OPENAI_API_KEY" not in env_config:
        openai_key = input("OpenAI API Key (for LLM functionality): ").strip()
        if openai_key:
            env_config["OPENAI_API_KEY"] = openai_key

    # Write .env file
    with open(env_file, "w") as f:
        f.write("# AgenticMemory Supabase Configuration\n")
        f.write("# Generated by setup script\n\n")

        for key, value in env_config.items():
            f.write(f"{key}={value}\n")

    print_success(f"Environment file created: {env_file.absolute()}")
    return True


def install_requirements():
    """Install Python requirements."""
    print_step("Installing Python requirements...")

    requirements_files = ["requirements.txt", "src/database/requirements_supabase.txt"]

    for req_file in requirements_files:
        if Path(req_file).exists():
            print(f"Installing from {req_file}...")
            try:
                subprocess.run(
                    [sys.executable, "-m", "pip", "install", "-r", req_file], check=True
                )
                print_success(f"Requirements from {req_file} installed")
            except subprocess.CalledProcessError as e:
                print_error(f"Failed to install requirements from {req_file}: {e}")
                return False
        else:
            print_warning(f"Requirements file not found: {req_file}")

    return True


def setup_supabase_database():
    """Guide user through setting up Supabase database."""
    print_step("Setting up Supabase database...")

    schema_file = Path("src/database/supabase_schema.sql")
    if not schema_file.exists():
        print_error(f"Schema file not found: {schema_file}")
        return False

    print("\nTo set up your Supabase database:")
    print(f"1. Open your Supabase project dashboard")
    print(f"2. Go to the SQL Editor")
    print(f"3. Copy and paste the contents of '{schema_file}'")
    print(f"4. Run the SQL script to create tables and functions")

    print(f"\nAlternatively, you can run:")
    print(f"supabase db reset --local")
    print(f"supabase db push")

    setup_complete = (
        input("\nHave you set up the database schema? (y/n): ").lower().startswith("y")
    )

    if setup_complete:
        print_success("Database setup completed")
        return True
    else:
        print_warning("Please complete the database setup before proceeding")
        return False


def test_connection():
    """Test the Supabase connection."""
    print_step("Testing Supabase connection...")

    try:
        # Add the src directory to Python path
        src_path = Path(__file__).parent.parent
        sys.path.insert(0, str(src_path))

        from database.supabase_config import SupabaseConfigManager
        from database.supabase_client import SupabaseMemoryClient

        # Test connection
        config_manager = SupabaseConfigManager()
        client = SupabaseMemoryClient(config_manager)

        # Try a simple operation
        stats = client.get_memory_stats()
        print_success("Supabase connection successful!")
        print(f"   Database stats: {stats}")
        return True

    except Exception as e:
        print_error(f"Supabase connection failed: {e}")
        print("\nPlease check:")
        print("- Your Supabase URL and keys are correct")
        print("- Your database schema is set up properly")
        print("- Your internet connection is working")
        return False


def main():
    """Main setup function."""
    print_header("AgenticMemory Supabase Setup")
    print("This script will help you set up Supabase integration for AgenticMemory.")

    # Check prerequisites
    if not check_python_version():
        return False

    # Check Supabase CLI
    if not check_supabase_cli():
        if not install_supabase_cli():
            print_warning(
                "Supabase CLI installation failed, but you can continue without it"
            )

    # Install requirements
    if not install_requirements():
        print_error("Failed to install requirements")
        return False

    # Create environment file
    if not create_env_file():
        print_error("Failed to create environment file")
        return False

    # Setup database
    if not setup_supabase_database():
        print_warning("Database setup incomplete")

    # Test connection
    test_connection()

    print_header("Setup Complete!")
    print("Your Supabase integration is now configured.")
    print("\nNext steps:")
    print("1. Run the Flask API: python src/api/chat_api.py")
    print("2. Test the integration: python src/api/test_supabase_api.py")
    print("3. Open the demo: http://localhost:5000/demo")

    print("\nFor more information, see:")
    print("- src/database/README.md")
    print("- Supabase documentation: https://supabase.com/docs")

    return True


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print_error(f"Setup failed with error: {e}")
        sys.exit(1)
